metadata_dir = "/var/lib/garage/meta"
data_dir = "/var/lib/garage/data"

replication_factor = 1
rpc_secret = "b5789b18766e3c0ebb2edd67c1fe3734cfc5da23dfdcca13c7ccd62797586ed6"
rpc_bind_addr = "[::]:3901"
rpc_public_addr = "garage:3901"


[s3_api]
bind_addr = "[::]:3900"
s3_region = "garage"

[admin]
bind_addr = "[::]:3903"
